name:                crispytoes
version:             0.1.0.0
github:              "qoelet/crispytoes"
license:             BSD3
author:              "Kenny Shen"
maintainer:          "kenny@machinesung.com"
copyright:           "2018 Kenny Shen"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/qoelet/crispytoes#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Crispy

tests:
  crispytoes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crispytoes
      - hspec
      - QuickCheck
